Resume.Web/Areas/Admin/Controllers/ContactUsController.cs
using Microsoft.AspNetCore.Mvc;
using Resume.Bussines.Services.Interface;
using Resume.DAL.ViewModels.ContactUs;
using Resume.DAL.ViewModels.User;

namespace Resume.Web.Areas.Admin.Controllers
{
    public class ContactUsController : AdminBaseController
    {
        #region Fields

        private readonly IContactUsService _contactUsService;

        #endregion

        #region Constructor

        public ContactUsController(IContactUsService contactUsService)
        {
            _contactUsService = contactUsService;
        }

        #endregion


        #region Actions

        #region List

        public async Task<IActionResult> List(FilterContactUsViewModel filter)
        {
            var model = await _contactUsService.FilterAsync(filter);
            return View(model);
        }

        #endregion

        #region Details

        public async Task<IActionResult> Details(int id)
        {
            var contactUs = await _contactUsService.GetByIdAsync(id);

            if (contactUs == null)
            {
                return NotFound();
            }

            return View(contactUs);
        }

        [HttpPost]
        public async Task<IActionResult> Details(ContactUsDetailsViewModel model)
        {
            #region Validations

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            #endregion

            var result = await _contactUsService.AnswerAsync(model);
            switch (result)
            {
                case AnswerResult.Success:
                    TempData[SuccessMessage] = "پاسخ برای این تماس با ما ارسال شد.";
                    return RedirectToAction("List");

                case AnswerResult.ContactUsNotFound:
                    TempData[ErrorMessage] = "تماس با ما پیدا نشد.";
                    break;

                case AnswerResult.AnswerIsNull:
                    TempData[ErrorMessage] = "متن پاسخ خالی است.";
                    break;

            }

            return View(model);
        }

        #endregion

        #endregion

    }
}

Resume.Web/Components/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Resume.Bussines.Services.Interface;

namespace Resume.Web.Components;

public class HeaderViewComponent:ViewComponent
{
    #region Fields

    private readonly IAboutMeService _aboutMeService;

    #endregion

    #region Constructor

    public HeaderViewComponent(IAboutMeService aboutMeService)
    {
        _aboutMeService = aboutMeService;
    }

    #endregion

    #region Method

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var model = await _aboutMeService.GetClientSideInfoAsync();
        return View("Header", model);
    }

    #endregion
}

Resume.Web/Controllers/AboutMeController.cs
using Microsoft.AspNetCore.Mvc;
using Resume.Bussines.Services.Interface;

namespace Resume.Web.Controllers
{
    public class AboutMeController : SiteBaseController
    {
        #region Fields

        private readonly IAboutMeService _aboutMeService;

        #endregion

        #region Constructor

        public AboutMeController(IAboutMeService aboutMeService)
        {
            _aboutMeService = aboutMeService;
        }

        #endregion

        #region Actions

        #region Index

        [HttpGet("/")]
        public async Task<IActionResult> Index()
        {
            var model = await _aboutMeService.GetClientSideInfoAsync();
            return View(model);
        }

        #endregion

        #endregion
    }
}

Resume.Web/Views/Shared/_Footer.cshtml
<!-- Footer -->
<footer class="footer">یاسمین یعقوبی</footer>

Resume.Web/Views/Shared/_FooterReferences.cshtml
<!-- JavaScripts -->
<script src="/Site/assets/js/jquery-3.4.1.min.js"></script>
<script src="/Site/assets/js/plugins.min.js"></script>
<script src="/Site/assets/js/common.js"></script>

<script src="/Site/assets/demo/plugins-demo.js"></script>

Resume.Web/Views/Shared/_HeaderReferences.cshtml
<!-- Favicons -->
<link rel="apple-touch-icon" sizes="144x144" href="/Site/assets/images/favicons/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="114x114" href="/Site/assets/images/favicons/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="72x72" href="/Site/assets/images/favicons/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="57x57" href="/Site/assets/images/favicons/apple-touch-icon-57x57.png">
<link rel="shortcut icon" href="/Site/assets/images/favicons/favicon.png" type="image/png">

<!-- Styles -->
<link rel="stylesheet" type="text/css" href="/Site/assets/styles/style-rtl-demo.css" />
<link rel="stylesheet" type="text/css" href="/Site/assets/styles/style-rtl.css" />
<link rel="stylesheet" type="text/css" href="/Site/assets/demo/style-demo.css" />
<link rel="stylesheet" type="text/css" href="/Site/assets/styles/site-custom.css" />

Resume.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa">
<head>

    <partial name="_MetaTags"/>

    <title>@ViewData["Title"]یاسمین یعقوبی | </title>

    <partial name="_HeaderReferences"/>
    @await RenderSectionAsync("Styles",false)

</head>
<body>
<!-- Preloader -->
<partial name="_Loader"/>


<main class="main">
    <!-- Header Image -->
    <partial name="_TopHeader"/>

    <div class="container gutter-top">

        @await Component.InvokeAsync("Header")

        <div class="row sticky-parent">
            <!-- Sidebar nav -->
            <partial name="_SideBar"/>

            <!-- Content -->
            <div class="col-12 col-md-12 col-lg-10">

                @RenderBody()

                <partial name="_Footer"/>
            </div>
        </div>
    </div>
</main>



<partial name="_FooterReferences"/>
@await RenderSectionAsync("Scripts",false)
</body>
</html>

Resume.Web/Views/Shared/_Loader.cshtml
<div class="preloader">
    <div class="preloader__wrap">
        <div class="circle-pulse">
            <div class="circle-pulse__1"></div>
            <div class="circle-pulse__2"></div>
        </div>
        <div class="preloader__progress">
            <span></span>
        </div>
    </div>
</div>

Resume.Web/Views/Shared/_MetaTags.cshtml
<meta charset="utf-8" />

<!-- Meta Data -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="format-detection" content="telephone=no"/>
<meta name="format-detection" content="address=no"/>
<meta name="author" content="yasaminyaqoonbi" />
<meta name="description" content="vCard" />

<!-- Twitter data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="ali">
<meta name="twitter:title" content="vCard">
<meta name="twitter:description" content="vCard">
<meta name="twitter:image" content="/Site/assets/images/social.html">

<!-- Open Graph data -->
<meta property="og:title" content="yasaminyghoobi" />
<meta property="og:type" content="website" />
<meta property="og:url" content="your url website" />
<meta property="og:image" content="/Site/assets/images/social.html" />
<meta property="og:description" content="vCard" />
<meta property="og:site_name" content="vCard" />

Resume.Web/Views/Shared/_SideBar.cshtml
<aside class="col-12 col-md-12 col-lg-2">
    <div class="sidebar box sticky-column">
        <ul class="nav">
            <li class="nav__item">
                <a class="active" asp-area="" asp-controller="AboutMe" asp-action="Index"><i class="icon-user"></i>درباره ی من</a>
            </li>
            <li class="nav__item">
                <a href="resume.html"><i class="icon-file-text"></i>رزومه</a>
            </li>
            <li class="nav__item">
                <a href="works.html"><i class="icon-codesandbox"></i> کارها</a>
            </li>
            <li class="nav__item">
                <a href="blog.html"><i class="icon-book-open"></i>وبلاگ</a>
            </li>
            <li class="nav__item">
                <a asp-controller="ContactUs" asp-action="ContactUs"><i class="icon-book"></i>تماس با ما</a>
            </li>
        </ul>
    </div>
</aside>

Resume.Web/Views/Shared/_TopHeader.cshtml
<div class="header-image">
            <div class="js-parallax" style="background-image: url(/Site/assets/img/image_header.jpg);"></div>
        </div>