Resume.Web/Areas/Admin/Components/LeftSideBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Resume.Bussines.Extensions;
using Resume.Bussines.Services.Interface;

namespace Resume.Web.Areas.Admin.Components;

public class LeftSideBarViewComponent : ViewComponent
{
    #region Fields

    private readonly IUserService _userService;

    #endregion

    #region Constructor

    public LeftSideBarViewComponent(IUserService userService)
    {
        _userService = userService;
    }

    #endregion

    #region Methods

    public async Task<IViewComponentResult> InvokeAsync()
    {
        ViewData["User"] = await _userService.GetInformationAsync(User.GetUserId());
        return View("LeftSideBar");
    }

    #endregion
}

Resume.Web/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <partial name="_MetaTags"/>
    <title>ادمین | @ViewData["Title"]</title>

    <partial name="_HeaderReferences"/>

</head>

<body class="light rtl">

<partial name="_Loader"/>

<div class="overlay"></div>

<partial name="_TopNavBar"/>

@await Component.InvokeAsync("LeftSideBar")

<section class="content">
    <div class="container-fluid">
        @RenderBody()
    </div>
</section>
<partial name="_FooterReferences"/>

</body>

Resume.Web/Areas/Admin/Views/Shared/_AdminNotFound.cshtml
<div class="alert alert-info mb-0">
    آیتمی پیدا نشد.
</div>

Resume.Web/Areas/Admin/Views/Shared/_AdminPagination.cshtml
@using Resume.DAL.ViewModels.Common
@model PagingViewModel

<div class="row">
    <div class="col-sm-12 col-md-12">
        <div class="dataTables_paginate paging_simple_numbers d-flex justify-content-center" id="tableGroup_paginate">
            <ul class="pagination">
                @for (int i = Model.StartPage; i <= Model.EndPage; i++)
                {
                    <li class="paginate_button page-item @(Model.Page==i?"active":"")">
                        <a onclick="fillPageId('@i')" aria-controls="tableGroup" data-dt-idx="@i" tabindex="0" class="page-link">
                            @i
                        </a>
                    </li>
                }
            </ul>
        </div>
    </div>
</div>

Resume.Web/Areas/Admin/Views/Shared/_FooterReferences.cshtml
<!-- Plugins Js -->
    <script src="/Admin/assets/js/app.min.js"></script>
    <script src="/Admin/assets/js/chart.min.js"></script>
    <!-- Custom Js -->
    <script src="/Admin/assets/js/admin.js"></script>
    <script src="/Admin/assets/js/bundles/apexcharts/apexcharts.min.js"></script>
    <script src="/Admin/assets/js/pages/index.js"></script>
    <script src="/Admin/assets/js/admin-custom.js"></script>

Resume.Web/Areas/Admin/Views/Shared/_HeaderReferences.cshtml
<!-- Favicon-->
<link rel="icon" href="/Admin/assets/images/favicon.ico" type="image/x-icon">
<!-- Plugins Core Css -->
<link href="/Admin/assets/css/app.min.css" rel="stylesheet">
<link href="/Admin/assets/js/bundles/materialize-rtl/materialize-rtl.min.css" rel="stylesheet">
<!-- Custom Css -->
<link href="/Admin/assets/css/style.css" rel="stylesheet" />
<!-- Theme style. You can choose a theme from css/themes instead of get all themes -->
<link href="/Admin/assets/css/styles/all-themes.css" rel="stylesheet" />

Resume.Web/Areas/Admin/Views/Shared/_Loader.cshtml
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="m-t-30">
            <img class="loading-img-spin" src="/Admin/assets/images/loading.png" alt="admin">
        </div>
        <p>لطفا صبر کنید...</p>
    </div>
</div>

Resume.Web/Areas/Admin/Views/Shared/_MetaTags.cshtml
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta content="width=device-width, initial-scale=1" name="viewport" />

Resume.Web/Areas/Admin/Views/Shared/_TopNavBar.cshtml
<!-- Top Bar -->
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="#" onClick="return false;" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse"
               aria-expanded="false">
            </a>
            <a href="#" onClick="return false;" class="bars"></a>
            <a class="navbar-brand" href="index.html">
                <img src="/Admin/assets/images/logo.png" alt=""/>
                <span class="logo-name">آتریو</span>
            </a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-left">
                <li>
                    <a href="#" onClick="return false;" class="sidemenu-collapse">
                        <i class="nav-hdr-btn ti-align-left"></i>
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <!-- Full Screen Button -->
                <li class="fullscreen">
                    <a href="javascript:;" class="fullscreen-btn">
                        <i class="nav-hdr-btn ti-fullscreen"></i>
                    </a>
                </li>
                <!-- #END# Full Screen Button -->
                <!-- #START# Notifications-->
                <li class="dropdown">
                    <a href="#" onClick="return false;" class="dropdown-toggle" data-toggle="dropdown" role="button">
                        <i class="nav-hdr-btn ti-bell"></i>
                        <span class="notify"></span>
                        <span class="heartbeat"></span>
                    </a>
                    <ul class="dropdown-menu pullDown">
                        <li class="header">اطلاعیه ها</li>
                        <li class="body">
                            <ul class="menu">
                                <li>
                                    <a href="#" onClick="return false;">
                                        <span class="table-img msg-user">
                                            <img src="/Admin/assets/images/user/user1.jpg" alt="">
                                        </span>
                                        <span class="menu-info">
                                            <span class="menu-title">حسین حیاتی</span>
                                            <span class="menu-desc">
                                                <i class="material-icons">access_time</i> 14 دقیقه پیش
                                            </span>
                                            <span class="menu-desc">لطفا ایمیل خود را چک کنید.</span>
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" onClick="return false;">
                                        <span class="table-img msg-user">
                                            <img src="/Admin/assets/images/user/user2.jpg" alt="">
                                        </span>
                                        <span class="menu-info">
                                            <span class="menu-title">حسین حیاتی</span>
                                            <span class="menu-desc">
                                                <i class="material-icons">access_time</i> 22 دقیقه پیش
                                            </span>
                                            <span class="menu-desc">لطفا ایمیل خود را چک کنید.</span>
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" onClick="return false;">
                                        <span class="table-img msg-user">
                                            <img src="/Admin/assets/images/user/user3.jpg" alt="">
                                        </span>
                                        <span class="menu-info">
                                            <span class="menu-title">حسین حیاتی</span>
                                            <span class="menu-desc">
                                                <i class="material-icons">access_time</i> 3 ساعت پیش
                                            </span>
                                            <span class="menu-desc">لطفا ایمیل خود را چک کنید.</span>
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" onClick="return false;">
                                        <span class="table-img msg-user">
                                            <img src="/Admin/assets/images/user/user4.jpg" alt="">
                                        </span>
                                        <span class="menu-info">
                                            <span class="menu-title">حسین حیاتی</span>
                                            <span class="menu-desc">
                                                <i class="material-icons">access_time</i> 3 ساعت پیش
                                            </span>
                                            <span class="menu-desc">لطفا ایمیل خود را چک کنید.</span>
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" onClick="return false;">
                                        <span class="table-img msg-user">
                                            <img src="/Admin/assets/images/user/user5.jpg" alt="">
                                        </span>
                                        <span class="menu-info">
                                            <span class="menu-title">حسین حیاتی</span>
                                            <span class="menu-desc">
                                                <i class="material-icons">access_time</i> 3 ساعت پیش
                                            </span>
                                            <span class="menu-desc">لطفا ایمیل خود را چک کنید.</span>
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" onClick="return false;">
                                        <span class="table-img msg-user">
                                            <img src="/Admin/assets/images/user/user6.jpg" alt="">
                                        </span>
                                        <span class="menu-info">
                                            <span class="menu-title">حسین حیاتی</span>
                                            <span class="menu-desc">
                                                <i class="material-icons">access_time</i> 3 ساعت پیش
                                            </span>
                                            <span class="menu-desc">لطفا ایمیل خود را چک کنید.</span>
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" onClick="return false;">
                                        <span class="table-img msg-user">
                                            <img src="/Admin/assets/images/user/user7.jpg" alt="">
                                        </span>
                                        <span class="menu-info">
                                            <span class="menu-title">حسین حیاتی</span>
                                            <span class="menu-desc">
                                                <i class="material-icons">access_time</i> دیروز
                                            </span>
                                            <span class="menu-desc">لطفا ایمیل خود را چک کنید.</span>
                                        </span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer">
                            <a href="#" onClick="return false;">مشاهده تمام اطلاعیه ها</a>
                        </li>
                    </ul>
                </li>
                <!-- #END# Notifications-->
                <li class="dropdown user_profile">
                    <div class="dropdown-toggle" data-toggle="dropdown">
                        <img src="/Admin/assets/images/user.jpg" alt="user">
                    </div>
                    <ul class="dropdown-menu pullDown">
                        <li class="body">
                            <ul class="user_dw_menu">
                                <li>
                                    <a href="#" onClick="return false;">
                                        <i class="material-icons">person</i>پروفایل
                                    </a>
                                </li>
                                <li>
                                    <a href="#" onClick="return false;">
                                        <i class="material-icons">feedback</i>بازخورد
                                    </a>
                                </li>
                                <li>
                                    <a href="#" onClick="return false;">
                                        <i class="material-icons">help</i>راهنما
                                    </a>
                                </li>
                                <li>
                                    <a href="#" onClick="return false;">
                                        <i class="material-icons">power_settings_new</i>خروج
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <!-- #END# Tasks -->
                <li class="pull-right">
                    <a href="#" onClick="return false;" class="js-right-sidebar" data-close="true">
                        <i class="nav-hdr-btn ti-layout-grid2"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- #Top Bar -->